# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a428074d6d68976943370e8ed0d2722cad56e4642a9a4d21e9a3c9eeea06a2b91b6963dc1f5c09504aff2daa2ab304cd84e693be2559aac49bd5cd4e6406b78

test:
  secret_key_base: 7b01a771f5b5eb966dab67d436c2dabd1fad764be78def9836652d2ce30e7231466160dd740eba38e65339b3da2e6a90eb325982e81c1d54c07c09c8b4751cac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
